Update action
music-encoding/music-encoding pull request #1033
Opened 2022-10-11 14:52 UTC by rettinghaus

This PR updates the used actions and combines the git steps.

2022-10-11 15:22 UTC, musicEnfanthen requested changes

2022-10-11 15:22 UTC, musicEnfanthen commented on .github/workflows/deploy.yml
> +          java-version: "17"
Is ant running with it?

2022-10-11 15:22 UTC, musicEnfanthen commented on .github/workflows/deploy.yml
>        - name: Set up JDK 1.8
```suggestion
      - name: Set up Java

2022-10-11 15:22 UTC, musicEnfanthen commented on .github/workflows/deploy.yml
> -      - name: Check git status before commit
I know that these three steps are somewhat verbose, but it helps to keep things separated (also for debugging). So would prefer not to combine them.

2022-10-11 15:22 UTC, musicEnfanthen commented on .github/workflows/deploy.yml
> -      - name: Check git status before commit
Same as above

2022-10-11 15:22 UTC, musicEnfanthen commented on .github/workflows/deploy.yml
> +    name: Build and deploy Schema
```suggestion
    name: Build and deploy Schema and Guidelines
```

2022-10-11 15:59 UTC, rettinghaus commented on .github/workflows/deploy.yml
> +          java-version: "17"
Yes, tested.

2022-10-12 14:45 UTC, musicEnfanthen commented on .github/workflows/deploy.yml
> +          java-version: "17"
Great

2022-10-12 14:46 UTC, musicEnfanthen commented on .github/workflows/deploy.yml
> -      - name: Check git status before commit
Thank you

2022-10-12 14:46 UTC, musicEnfanthen approved these changes

2022-10-12 19:34 UTC, bwbohl commented
@rettinghaus what do you mean with 
> combines the git steps

can't really see a big change, although I think the small ones make a big difference ;-)

2022-10-12 19:35 UTC, bwbohl commented
Moreover I'd rather see this merged to [pdf-guidelines-test ](https://github.com/music-encoding/music-encoding/tree/pdf-guidelines-test) which is the furthest development of the build process

2022-10-13 13:37 UTC, musicEnfanthen commented
@bwbohl This one updates the versions of different actions used right now (checkout, java setup, etc.). It should be fine to go for now in develop. The full script will be revised on pdf-guidelines-test for sure, but that is not primarily connected to this PR.

2022-10-13 20:00 UTC, bwbohl approved these changes

2022-10-13 20:00 UTC, merged