Fix issue 120 (guidelines repo)
music-encoding/music-encoding pull request #1037
Opened 2022-10-18 05:12 UTC by riedde

This PR fixes music-encoding/guidelines#120

- Renaming guidelines section 3.4.1.2 to prevent misunderstanding
- update example (invalid encoding)

The example tried to offer a list of possible encodings, but the wrapping element is not allowed for this case. Trying to keep the intention, I just deleted the wrapper and added comments to clarify that the encoded examples are substitutable.

2022-10-18 05:18 UTC, riedde commented
closes https://github.com/music-encoding/metadata-ig/issues/26

2022-10-18 07:16 UTC, kepper approved these changes, later dismissed
looks sensible to me

2022-10-20 12:20 UTC, musicEnfanthen requested changes

2022-10-20 12:20 UTC, musicEnfanthen commented on source/docs/03-metadata.xml
>                    <div xml:id="headerPhysicalDescription" type="div4">
```suggestion
                  <div xml:id="headerFileExtent" type="div4">
```

2022-10-20 12:21 UTC, musicEnfanthen commented on source/docs/03-metadata.xml
>                    <div xml:id="headerPhysicalDescription" type="div4">
Did not find any references to this id in the source, but would be good to double-check

2022-10-20 14:07 UTC, riedde commented on source/docs/03-metadata.xml
>                    <div xml:id="headerPhysicalDescription" type="div4">
Same here.

2022-10-20 17:16 UTC, musicEnfanthen approved these changes

2022-10-21 10:20 UTC, musicEnfanthen commented on source/docs/03-metadata.xml
>                    <div xml:id="headerPhysicalDescription" type="div4">
Great, thanks

2022-10-27 13:29 UTC, bwbohl approved these changes

2022-10-27 13:33 UTC, musicEnfanthen commented
Thank you @riedde

2022-10-27 13:33 UTC, merged