Guidelines Chapter 3: Updating list of authors
music-encoding/music-encoding pull request #1093
Opened 2023-03-18 12:15 UTC by riedde

This PR is a proposal by @music-encoding/ig-metadata
The authors of the texts are referenced by the `Co-authored-by` keyword.

_Please note:_ This PR is going to be merged into the branch `ig-metadata`!

Reviews and constructive suggestions are welcome!

2023-04-27 15:56 UTC, bwbohl approved these changes

2023-04-27 15:59 UTC, musicEnfanthen requested changes
Use Github name if no real name is provided via GH API

2023-04-27 15:59 UTC, musicEnfanthen commented on source/docs/03-metadata.xml
> +               <name ref="https://api.github.com/users/irmlindcapelle">Irmlind Capelle</name>
```suggestion
               <name ref="https://api.github.com/users/irmlindcapelle">irmlindcapelle</name>
```

2023-04-27 15:59 UTC, musicEnfanthen commented on source/docs/03-metadata.xml
> +               <name ref="https://api.github.com/users/MajaHartwig">Maja Hartwig</name>
```suggestion
               <name ref="https://api.github.com/users/MajaHartwig">MajaHartwig</name>
```

2023-04-28 10:08 UTC, ahankinson commented
Is there a reason the GitHub API URI is preferred over ORCID or VIAF?

2023-06-14 10:42 UTC, musicEnfanthen commented on source/docs/03-metadata.xml
> +               <name ref="https://api.github.com/users/doerners">Sophia Dörner</name>
Move "Dörner" above "Dubowy"

2023-06-14 10:42 UTC, musicEnfanthen commented on source/docs/03-metadata.xml
> +               <name ref="https://api.github.com/users/gucl-mu">gucl-mu</name>
Move "gucl-mu" above "Hankinson"

2023-06-14 10:46 UTC, musicEnfanthen commented
@ahankinson At the moment, it is consistently with only GitHub API. But yes, we should discuss with the @music-encoding/guidelines-editors if we want to be limited to those in the future.

2023-06-16 09:51 UTC, musicEnfanthen commented on source/docs/03-metadata.xml
@riedde I cannot push directly to this PR, so please change the list to the following:

```
               <name ref="https://api.github.com/users/bwbohl">Benjamin W. Bohl</name>
               <name ref="https://api.github.com/users/BruxDDay">BruxDDay</name>
               <name ref="https://api.github.com/users/elsinhadl">Elsa De Luca</name>
               <name ref="https://api.github.com/users/dinamix">dinamix</name>
               <name ref="https://api.github.com/users/doerners">Sophia Dörner</name>
               <name ref="https://api.github.com/users/ndubo">Norbert Dubowy</name>
               <name ref="https://api.github.com/users/fujinaga">Ichiro Fujinaga</name>
               <name ref="https://api.github.com/users/axgeertinger">Axel Geertinger</name>
               <name ref="https://api.github.com/users/gucl-mu">gucl-mu</name>
               <name ref="https://api.github.com/users/ahankinson">Andrew Hankinson</name>
               <name ref="https://api.github.com/users/irmlindcapelle">irmlindcapelle</name>
               <name ref="https://api.github.com/users/frakel">franz kelnreiter</name>
               <name ref="https://api.github.com/users/kepper">kepper</name>
               <name ref="https://api.github.com/users/zolaemil">Zoltan Komives</name>
               <name ref="https://api.github.com/users/DDMAL-LabManager">DDMAL LabManager</name>
               <name ref="https://api.github.com/users/uliska">Urs Liska</name>
               <name ref="https://api.github.com/users/napulen">Néstor Nápoles López</name>
               <name ref="https://api.github.com/users/MajaHartwig">MajaHartwig</name>
               <name ref="https://api.github.com/users/musicEnfanthen">Stefan Münnich</name>
               <name ref="https://api.github.com/users/pe-ro">pe-ro</name>
               <name ref="https://api.github.com/users/lpugin">Laurent Pugin</name>
               <name ref="https://api.github.com/users/JRegimbal">Juliette Regimbal</name>
               <name ref="https://api.github.com/users/rettinghaus">Klaus Rettinghaus</name>
               <name ref="https://api.github.com/users/riedde">Dennis Ried</name>
               <name ref="https://api.github.com/users/mss2221">Mark Saccomano</name>
               <name ref="https://api.github.com/users/aseipelt">Agnes Seipelt</name>
               <name ref="https://api.github.com/users/margrethesb">Margrethe Støkken Bue</name>
               <name ref="https://api.github.com/users/martha-thomae">Martha E. Thomae</name>
               <name ref="https://api.github.com/users/raffazizzi">Raffaele Viglianti</name>
               <name ref="https://api.github.com/users/vigliensoni">Gabriel Vigliensoni</name>
               <name ref="https://api.github.com/users/th-we">Thomas Weber</name>
               <name ref="https://api.github.com/users/musicog">David M. Weigl</name>
```

2023-06-16 15:20 UTC, riedde commented on source/docs/03-metadata.xml
Done on https://github.com/music-encoding/music-encoding/pull/1093/commits/70870ac7e4be9743d5015f88a57a64e5c7e39b0c

2023-06-16 20:36 UTC, musicEnfanthen approved these changes

2023-06-16 20:36 UTC, merged