Clear up description of line rendition
music-encoding/music-encoding pull request #1225
Opened 2023-06-16 14:09 UTC by rettinghaus

Attempt to fix #1224.

2023-06-16 14:14 UTC, ahankinson requested changes

2023-06-16 14:14 UTC, ahankinson commented on source/docs/02-shared.xml
> +                  <p>In addition to these textual values, the width attribute may contain a numeric value and an optional unit value, <val>2mm</val> for example. If the unit value is not provided MEI
```suggestion
                  <p>In addition to textual values, the <att>width</att> attribute may contain a numeric value and an optional unit, <abbr>e.g.</abbr>, <val>2mm</val>. If the unit value is not provided, MEI virtual units are presumed.</p>
```

2023-06-16 14:14 UTC, ahankinson commented on source/docs/02-shared.xml
> +                  <p>Same applies for <gi scheme="MEI">curve</gi> elements with the <att>lform</att> and <att>lwidth</att> attributes from the <ident type="class">att.curveRend</ident> class.</p>
```suggestion
                  <p>The same applies for <gi scheme="MEI">curve</gi> elements with the <att>lform</att> and <att>lwidth</att> attributes from the <ident type="class">att.curveRend</ident> class.</p>
```

2023-06-16 14:23 UTC, rettinghaus commented on source/docs/02-shared.xml
> +                  <p>Same applies for <gi scheme="MEI">curve</gi> elements with the <att>lform</att> and <att>lwidth</att> attributes from the <ident type="class">att.curveRend</ident> class.</p>
Thanks.

2023-06-16 14:26 UTC, ahankinson approved these changes

2023-06-20 20:27 UTC, bwbohl approved these changes

2023-06-20 20:58 UTC, merged