Replace version 5.0 with dev
music-encoding/music-encoding pull request #1386
Opened 2023-10-26 13:48 UTC by musicEnfanthen

Following the 5.0 release, the content of the develop branch was identical to that of the stable branch. This pull request restores the dev version for the develop branch.

The proposed solution involves using `dev+...` as the version name/number, eliminating the need to definitely determine the next version number.

However, it is still up for discussion whether to use `6.0-dev+...`, `5.1-dev+...`, or another naming convention.

2023-10-26 13:50 UTC, musicEnfanthen commented
Reviewers: Whatever version name we'll choose, please double check if I missed some instance of the version in the repository.

2023-10-26 14:08 UTC, lpugin commented
Is the plan to have things like `@meiversion="dev+all"`? I am not fully convinced that this is a good idea. In an ideal world, they should be no MEI files using a development schema outside development sandboxes. However, we know this is not the case, and with this change we will be having MEI files with no indication which development phase they relate or related to.

2023-10-26 15:41 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +          <valItem ident="dev">
```suggestion
          <valItem ident="5.0+dev">
```

2023-10-26 15:51 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +          <valItem ident="dev+anyStart">
```suggestion
          <valItem ident="5.1+anyStart-dev">
```

2023-10-26 15:58 UTC, ahankinson commented
Not to be "that guy" but I thought we had agreed that the next release is 6?

2023-10-26 16:10 UTC, musicEnfanthen commented
Valid point as well. The reasoning we discussed today during the ODD meeting is the following:

The idea behind 5.1-dev would be to keep a door open for a possible interim release, but if that is not needed, we could go from 5.1-dev directly to 6.0. But with 6.0-dev it would be harder to go for a possible 5.1 release (whether it is needed or not).

What do you think?

2023-10-28 09:44 UTC, ahankinson commented
I think the likelihood that we’ll do a 5.1 release is pretty low. Even if we want to keep with SemVer (I’m not convinced it’s a good fit for what we’re doing), @pe-ro has already filed a number of PRs, many of which would necessitate a major version release when they’re merged. I don’t think it’s useful to artificially delay their acceptance after review simply because we need to make our version numbers make sense. As I’ve said before, tracking compatibility changes is really tricky, and the solution is just to agree that we don’t actually need to do it. 

The next merge of develop to main is 6. Then the next merge is 7. And the next is 8. That’s it. Do we really need anything more complicated than that? Or, put another way, has anyone really done anything with the previous point releases that they wouldn’t have done with a major release? Have point releases added any value at all? 

4.0.1 fixed a bug that was found in the schema that prevented the schema from actually working, but we didn’t actually gain anything with needing to update all the documents `meiversion` string to 4.0.1. It was all still MEI4.

2023-10-28 15:23 UTC, rettinghaus commented
We had an extensive discussion and a plethora of arguments on this topic. We can continue this indefinitely or just move forward. I'm fine with the decision made during the ODD meeting.

2023-10-28 15:27 UTC, rettinghaus approved these changes, later dismissed

2023-10-28 16:48 UTC, ahankinson commented
Am I misremembering a different conclusion at the previous meeting?

2023-10-30 09:27 UTC, ahankinson commented
> The idea behind 5.1-dev would be to keep a door open for a possible interim release, but if that is not needed, we could go from 5.1-dev directly to 6.0. But with 6.0-dev it would be harder to go for a possible 5.1 release (whether it is needed or not).

> What do you think?

OK, I've been thinking about this all weekend. @rettinghaus is right -- we do seem to keep circling the drain here. But at the same time, I honestly think that our adherence to SemVer is causing more problems than it solves because we don't really know what we're versioning.

At the same time, I recognize that some wish to have a system in place to help manage the source code.* 

So what about this as an alternate proposal? Rather than `{major}.{minor}` we understand the version numbers to be `{compatibility}.{updates}`. That is, the `compatibility` value gives a digit for indicating document compatibility, while we use the second digit as a source control digit to indicate updates to the source code that do not break compatibility. 

**The key here is that `@meiversion` is changed to only take the `{compatibility}` value.** Any other place (e.g., GH tags, URLs?) we can use the full version. Given that the compatibility shouldn't change from a 5.0 to a 5.1 release, this should be no problem. (And if we **do** find the changes we have put in break compatibility, that would be a clear indicator that we need to bump up the compatibility version.)

The thinking behind this is that the `@meiversion` value is the *only* interface between a version number and a tagged release. Moving to a single digit here means that we're not "breaking" compatibility artificially by only changing this value with point updates. (As a reminder: Releasing "5.1" under the current scheme, regardless of whether it contains schema changes, would necessitate changing `@meiversion` values which, in itself, would break compatibility.)

Thus, if people are producing MEI 5 documents, and nothing actually changes in the validation, then their documents wouldn't actually have to change either. They can use a MEI 5.0 schema to validate an MEI 5.1 document, since the values in the schema wouldn't change either. 5.1 would be an administrative change only.

This also bypasses the whole conversation on what constitutes a "breaking" change. Any change that means that a "compatibility 5" schema is no longer able to validate a "compatibility 5" document is a "breaking" change.

So let's look at a few scenarios:

 - The ODD2ODD refactor. This shouldn't change any compatibility, so it would just be an `{update}` level change.
 - Updating documentation. Also shouldn't change any compatibility, so it would just be an `{update}` level change.
 - Adding a new value for an attribute. This *would* break compatibility, so would necessitate a `{compatibility}` level change. 
 - Adding / removing elements or attributes. Also are compatibility-breaking changes.
 - Adding / removing child or parent elements. This is also a compatibility-breaking change.
 - Adding / removing / changing a customization. I think we need to consider customizations part of the "core" since all schemas are expressed through customizations (IOW, we don't have the "MEI All" schema without the "MEI All" customization. So modifying any values in the customization that change elements / attributes and hierarchy would break this.
 - Adding schematron rules. This is a tricky one, but I think we should consider schematron part of the validation, and changes to the schematron rules that raise new **errors** are breaking changes. New **warnings** can be considered administrative changes. (This can also be managed with a guided upgrade, e.g., we can raise a warning and say that in the next version it will be an error.)

So, To avoid a breaking change, the current value of `@meiversion` can be expanded to include `5`, `5+anyStart`, `5+basic`, etc. Since any 5.0 schema would also be a valid 5.1 schema, I don't think we need to remove the existing `5.0...` values, but we simply never increment this number. This would then get normalized in 6.

---

* RE: Source code. To explain my thinking further, what might be happening is a divide between thinking of MEI as "source code" vs. thinking of it as "a set of rules."  For me, the XML is simply a way of expressing a set of rules, and those rules are what MEI is. If, tomorrow, we were to do away with XML and change MEI to a JSON format, the rules for encoding MEI would not actually change. So what I'm trying to communicate is that we can look at this as versioning the rules, not the actual expression of these rules in XML / ODD / RNG / Whatever.

It may be that others are thinking of the MEI Schema as a set of source code that needs to be managed as source code. If you think of the XML as being integral to MEI, and commits to the XML necessitate these sorts of changes, then this may explain why SemVer is an important system to follow. I personally don't think this way (anymore... I did once) but I recognize that some do.

So the thinking behind my proposal above is to try and reconcile the two: That is, we have a versioning for the "rules" of MEI, and then a second level of versioning for the "expression" of those rules in source code. The source code versioning can function in all the places the source code versioning is important (git, tags, etc.) while the compatibility versioning functions in the places where it is important (indicating whether a document is "valid" to a specific set of MEI rules.)

2023-10-30 12:40 UTC, lpugin commented
I am fine with the idea to have MEI version numbers being a single number. That is, `@meiversion="x"` and not `@meiversion="x.x"` as we have now or `@meiversion="x.x.x` before.

Since we are now on version `5.0`, it would not really work to add `5` as possible version number in the next update since then `@meiversion="5"` files would not be valid with the current (5.0) schema. If we go with @ahankinson's proposal, that would really work from version `6` onwards.

For the time being, I would suggest staying with `5.1-dev`. If we have changes merged into the schema that break compatibility in the way we understood it so far (all files valid with `5.0` should also be valid with `5.1`, but not necessary the opposite) then we would move to `6-dev` and drop the second number for the version at that point only. As @musicEnfanthen we do not necessary have to have a `5.1` and we can directly move to `6`. I would say that it will be to the technical co-chairs to decide if and when that should happen, namely for them to merge or not merge PRs depending on the consequences and the desired next release.

Does this sound reasonable?

2023-11-01 12:27 UTC, ahankinson commented
@lpugin yes, that sounds reasonable. 

On the understanding that moving to a single-digit `@meiversion` now would break compatibility, I'll approve the general direction of this change. I still have my reservations that 5.1 will ever see the light of day, but I guess that's a problem for future us?

2023-11-01 12:28 UTC, ahankinson commented on source/modules/MEI.shared.xml
> +        <defaultVal>dev</defaultVal>
`5.1-dev`?

2023-11-01 12:30 UTC, ahankinson commented on customizations/mei-all.xml
> +              <defaultVal>dev</defaultVal>
`5.1-dev`?

2023-11-01 12:31 UTC, ahankinson submitted a review, later dismissed
I think there were a few changes skipped? I marked them but didn't set them as a suggestion because I wasn't sure if it was intentional or not?

2023-11-21 15:58 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +        <defaultVal>dev</defaultVal>
```suggestion
        <defaultVal>5.1-dev</defaultVal>
```

2023-11-21 16:11 UTC, bwbohl requested changes

2023-11-21 16:11 UTC, bwbohl commented on customizations/mei-all.xml
> +              <defaultVal>dev</defaultVal>
```suggestion
              <defaultVal>5.1-dev</defaultVal>
```

2023-11-21 16:11 UTC, bwbohl commented on customizations/mei-all_anyStart.xml
> +              <defaultVal>5.1-dev+anyStart</defaultVal>
```suggestion
```

2023-11-21 16:11 UTC, bwbohl commented on customizations/mei-all_anyStart.xml
> +              <defaultVal>5.1-dev+anyStart</defaultVal>
We should remove the defaultVal for anyStart to accomodate / fix #1347

2023-11-21 16:11 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +        <defaultVal>dev</defaultVal>
```suggestion
        <defaultVal>5.1-dev</defaultVal>
```

2023-11-21 16:11 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +            <desc xml:lang="en">Development version of MEI 6.0</desc>
```suggestion
            <desc xml:lang="en">Development version</desc>
```

2023-11-21 16:11 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +            <desc>Development version of MEI 6.0+anyStart</desc>
```suggestion
            <desc>Development version</desc>
```

2023-11-21 16:11 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +              <desc>Development version of MEI 6.0+basic</desc>
```suggestion
              <desc>Development version</desc>
```

2023-11-21 16:11 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +            <desc>Development version of MEI 6.0+CMN</desc>
```suggestion
            <desc>Development version</desc>
```

2023-11-21 16:11 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +            <desc>Development version of MEI 6.0+Mensural</desc>
```suggestion
            <desc>Development version</desc>
```

2023-11-21 16:11 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +            <desc>Development version of MEI 6.0+Neumes</desc>
```suggestion
            <desc>Development version</desc>
```

2023-11-24 16:15 UTC, rettinghaus approved these changes

2023-11-24 16:17 UTC, bwbohl approved these changes

2023-11-24 16:21 UTC, merged