fixing `@place` documentation for `<dynam>`
music-encoding/music-encoding pull request #1418
Opened 2024-01-19 11:37 UTC by riedde

Closes #1411 
Co-authored-by: @jannikFranz
Co-authored-by: @ohwjd

2024-01-19 12:32 UTC, rettinghaus requested changes
`between` needs exactly two (consecutive) staves.

2024-01-19 12:32 UTC, rettinghaus commented on source/docs/04-cmn.xml
> +                  <p>The location of a dynamic marking in relation to a staff may be specified using the <att>place</att> attribute, which may be given as <val>above</val>, <val>below</val> or <val>w
```suggestion
                  <p>The location of a dynamic marking in relation to a staff may be specified using the <att>place</att> attribute, which may be given as <val>above</val>, <val>below</val> or <val>within</val> the staff or even <val>between</val> two staves:</p>
```

2024-01-20 10:05 UTC, rettinghaus approved these changes

2024-01-20 11:02 UTC, musicEnfanthen approved these changes

2024-01-20 11:02 UTC, merged