Adjust `<p>` and `<div>` for specifying better text positioning
music-encoding/music-encoding pull request #1474
Opened 2024-05-23 21:26 UTC by lpugin

Relates to #1189

2024-05-23 22:08 UTC, lpugin commented
Also addresses #272

2024-05-25 17:37 UTC, rettinghaus commented
"A horizontal division" is a bit problematic as it could be read as "horizontally divided", but this is not exactly the point, Is it?

If I understood correctly it is about splitting a `div` into multiple vertically aligned parts right? Why not borrow `cb` (column beginning) from [TEI](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-cb.html)?

2024-05-25 18:59 UTC, lpugin commented
As you can see the `@func` is on the `div` and is meant to describe how the division interrupts the flow. When placed between two measures, a `<div func="hdiv"/>` represents a division within the system between the two measures, whereas a `<div func="vdiv"/>` is a vertical division (i.e., replacing a full system).

2024-05-30 09:53 UTC, rettinghaus commented
Thanks for the clarification. But I'm still not fully convinced of the benefits. 
You could do the same with 

```xml
<measure />
<div />
<measure />
```

for text between measures, and 

```xml
<measure />
<sb />
<div />
<sb />
<measure />
```

for divisions between systems.

2024-05-30 10:41 UTC, lpugin commented
That works if you want to use and rely on encoded layout (i.e., `sb`), but not if you do not want to have encoded `sb`. That is what `div@func` is there for.

2024-05-30 11:47 UTC, rettinghaus commented
Still, if you just put it between measures it depends on the content where a renderer would put it, especially if its content also is expected to layout automatically. If you want to say that it fills the space of a full system, then a boolean flag would be enough, something like `systemlike="true"`. But that would also be some sort of "layout" that you need to rely on. 
The best way is to make it explicit by putting it on a higher level between sections or, even better, between mDivs.

2024-05-30 13:22 UTC, lpugin commented
I do not see a major difference between `systemlike="true"` and `func="vdiv"`.

> The best way is to make it explicit by putting it on a higher level between sections or, even better, between mDivs

Because the number of levels of nesting of `section` is not constraint and not semantically bound to anything decided in MEI, your approach does not work. Just to give you one example: it would make it impossible to have a `hdiv` between two sections, which depending on what a section is in the piece, might be expected. Unless you introduce then `systemlike="false"` ...

2024-06-24 21:02 UTC, bwbohl commented
A bit late to the party, but wouldn’t it be good to add to the description of `att.horizontalAlign` and `att.verticalAlign` something about the scope of alignment or the reference box and that the attributes are about the placement of an element’s contents?

And for better understanding, @lpugin could you provide a "complete" encoding for the example page at the beginning of #1189

2025-02-27 15:17 UTC, lpugin commented on source/modules/MEI.shared.xml
> +      </attDef>
```suggestion
      <attDef ident="func" usage="opt">
        <desc xml:lang="en">Indicates whether the element acts as a measure or a system within the flow.</desc>
        <valList type="closed">
          <valItem ident="measure">
            <desc xml:lang="en">A measure division.</desc>
          </valItem>
          <valItem ident="system">
            <desc xml:lang="en">A system division.</desc>
          </valItem>
        </valList>
      </attDef>
```

2025-02-27 15:28 UTC, rettinghaus submitted a review, later dismissed

2025-02-27 15:28 UTC, rettinghaus commented on source/modules/MEI.shared.xml
> +        <desc xml:lang="en">Indicates whether the element acts as a measure or a system within the flow.</desc>
```suggestion
        <desc xml:lang="en">Indicates whether the element acts like a measure or a system within the flow.</desc>
```

2025-02-27 15:28 UTC, rettinghaus commented on source/modules/MEI.shared.xml
> +            <desc xml:lang="en">A measure division.</desc>
```suggestion
            <desc xml:lang="en">A measure-like division.</desc>
```

2025-02-27 15:28 UTC, rettinghaus commented on source/modules/MEI.shared.xml
> +            <desc xml:lang="en">A system division.</desc>
```suggestion
            <desc xml:lang="en">A system-like division.</desc>
```

2025-02-27 15:37 UTC, lpugin commented on source/modules/MEI.shared.xml
> +        <desc xml:lang="en">Indicates whether the element acts as a measure or a system within the flow.</desc>
Not sure about this one. Maybe an native English speaker can decide.

2025-02-27 15:38 UTC, lpugin commented on source/modules/MEI.shared.xml
> +        <desc xml:lang="en">Indicates whether the element acts as a measure or a system within the flow.</desc>
@ahankinson ?

2025-02-27 15:38 UTC, rettinghaus commented on source/modules/MEI.shared.xml
> +        <desc xml:lang="en">Indicates whether the element acts as a measure or a system within the flow.</desc>
@ahankinson ?

2025-07-23 08:39 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +        <desc xml:lang="en">Indicates whether the element acts as a measure or a system within the flow.</desc>
I think that both are valid alternatives; while `act as` emphasises a role, `act like` emphasises a behaviour. But what about adding a bit more verbosity, e.g.:
```suggestion
        <desc xml:lang="en">Specifies how the element is treated in terms of page flow: as inline element like a measure, or as block element like a system.</desc>
```

2025-12-01 13:40 UTC, rettinghaus submitted a review, later dismissed

2026-01-19 08:33 UTC, lpugin commented
May I ask what is missing for the PR to be approved?

2026-01-19 15:44 UTC, pe-ro commented
I don't have any objections to this PR, but it may be helpful to 

1. rename `@func` to `@rend` and
2. allow `@rend` to take the values "inline" and "block".

The name `@rend` is more in keeping with TEI and HTML since it carries info about the _appearance_ of the `<div>`.

The values "inline" and "block" are replacements for "hdiv" and "vdiv", respectively.  These terms are analogous to how objects; e.g., images, are labeled  in flowing text.  `<div func="inline">` indicates that the `<div>` does not interrupt the flow of measures; that is, it fits between measures (essentially taking the place of a measure or measures), while `<div func="block">` means that the `<div>` interrupts the flow of measures; that is, it takes the place of a system.

2026-01-30 15:28 UTC, bwbohl commented
MEI ODD meeting: Attribute name should be `@flow`with  values `inline` and `block`.

2026-01-30 15:34 UTC, bwbohl commented
@lpugin maybe you could also add the images from the issue to the guidelines for illustrative purposes

2026-03-06 16:57 UTC, bwbohl requested changes
MEI ODD meeting January: Attribute name should be `@flow` with values inline and block.

@lpugi,n maybe you could also add the images from the issue to the guidelines for illustrative purposes

2026-03-27 15:04 UTC, bwbohl commented
As agreed in today’s ODD meeting, let’s move the documentation section to chapter Text (whatever number) and then it’s good to go

2026-04-16 11:49 UTC, bwbohl submitted a review, later dismissed

2026-04-20 16:20 UTC, rettinghaus submitted a review, later dismissed

2026-05-05 07:46 UTC, bwbohl commented
GitHub seems to have issues processing my local branch update because the “update branch” button isn’t working… Issuing a new comparison or PR from lpugin:develop-div looks just fine, but this here doesn’t update (see “processing changes” at the top). We can wait just a bit longer or close and create a new PR. @lpugin, what do you think?

2026-05-05 07:46 UTC, bwbohl commented
cf. https://github.com/music-encoding/music-encoding/compare/develop...lpugin:music-encoding:develop-div

2026-05-05 08:39 UTC, lpugin commented
I updated it locally

2026-05-05 15:40 UTC, bwbohl commented
That's what I had done before but then it stopped working, great it worked for you!

2026-05-05 15:41 UTC, bwbohl approved these changes

2026-05-05 15:42 UTC, merged

2026-05-05 15:43 UTC, bwbohl commented
I merged it bypassing the requirement of two reviews because they had been there before and just got de-approved because of the local rebase