fix issue #1540
music-encoding/music-encoding pull request #1541
Opened 2024-10-21 14:27 UTC by janjusolja

Changing `<attList>` of `att.scoreDef.vis.tablature` and `att.stringtab`

This change is moving attributes `@tab.align` and `@tab.anchorline` from the list of attributes meant for string and fret information to the list of visual domain attributes of the element `<scoreDef>` .

Closes #1540

2024-10-21 14:53 UTC, rettinghaus requested changes
Wouldn't it make more sense to bring it to `staffDef`? There we have `@tab.courses` and `@tab.strings`, and as far as I understand, this should apply to one "staff", not the whole score.

2024-10-21 16:47 UTC, musicEnfanthen commented
@janjusolja Many thanks for the PR. 

As @rettinghaus mentioned, with this change the attributes will be available only on `scoreDef`.

So you would probably need to add a new classSpec for `att.staffDef.vis.tablature`:

```
  <classSpec ident="att.scoreDef.vis.tablature" module="MEI.stringtab" type="atts">
    <desc xml:lang="en">Visual domain attributes for scoreDef in the tablature repertoire.</desc>
  </classSpec>
  <classSpec ident="att.staffDef.vis.tablature" module="MEI.stringtab" type="atts">
    <desc xml:lang="en">Visual domain attributes for staffDef in the tablature repertoire.</desc>
    
    ... att list with tab.anchorline and tab.align here ...

```

And then add that class to [`att.staffDef.vis`](https://music-encoding.org/guidelines/dev/attribute-classes/att.staffDef.vis.html) in MEI.visual.xml (similar to `att.stafDef.vis.cmn` and `att.staffDef.vis.mensural`).

2024-10-22 07:03 UTC, janjusolja commented
Of course! Thank you @rettinghaus and @musicEnfanthen for the review. This was a basic brain trick while trying to do a quick fix: because the `att.scoreDef.vis.tablature` already existed and was empty, I automatically assumed that we had just missed a few codelines. Will be more careful in the future!

2024-10-22 07:16 UTC, rettinghaus approved these changes
LGTM, thank you!

2024-10-22 12:33 UTC, musicog approved these changes
Thanks @janjusolja! Looks good!

2024-10-23 11:49 UTC, musicEnfanthen approved these changes

2024-10-23 11:50 UTC, musicEnfanthen commented
Thank you @janjusolja . Also looks good to me.

Any additional thoughts/comments, @music-encoding/technical-team, @lpugin ?

2024-11-02 09:15 UTC, riedde approved these changes
Fine! Thank you!

2024-11-13 08:57 UTC, bwbohl approved these changes

2024-11-13 08:58 UTC, merged