added support for @stem.sameas
music-encoding/music-encoding pull request #586
Opened 2019-04-10 12:43 UTC by frakel

- extends att.stems class with @stem.sameas which is needed to correctly encode orchestral scores 
- adds support for notes that share one stem but are located in different layers
- fixes #551

2019-04-10 12:49 UTC, ahankinson commented
As this is a new feature, not a bugfix I would like to defer this for merging until after we handle #582 .

2019-04-12 13:51 UTC, ahankinson commented
The indents and formatting of the contribution seem to be different than the surrounding style; could you please re-format to match the existing style?

2019-04-18 08:55 UTC, ahankinson approved these changes

2019-05-21 12:43 UTC, lpugin commented
Can this be merged?

2019-06-21 11:30 UTC, kepper requested changes
In general, I agree. There is only one thing that isn't clear to me (yet), and that I would like to see clarified in the documentation at least: How does this relate to stems across staves? There should be at least a reference to the concepts for that, and a specific hint that `@stem.sameas` isn't intended to cover that use case. Or, if it is intended to cover that as well, the Schematron probably needs to be changed. All that could perhaps be blamed to my ignorance, but I still think others may run into the same issue…

2019-06-24 20:17 UTC, lpugin commented
@frakel : could you clarify this?

2019-06-27 15:36 UTC, frakel commented
It does not relate in any case to stems across staves as `@stem.sameas` is meant to work only in one stave with two layers. 
It has absolutely nothing to do with crossing staves, as the two layers with the corresponding notes have to be in the same staff. `@stem.with` covers a totally different issue. I can add this to the description if necessary.

2019-07-16 12:51 UTC, kepper commented
I would actually like to see a sentence about `@stem.with` in the `<desc>` of this. I would also love to have a paragraph about these two in the guidelines. @frakel, could you please add something as soon as you're back? Thanks :-)

2019-07-31 08:58 UTC, bwbohl requested changes
Basically I do approve, except for the one change in CONTRIBUTING.md and considering the change to the <desc> is made according to @kepper 's request.

Thanks you very much!

2019-07-31 08:58 UTC, bwbohl commented on CONTRIBUTING.md
> +### Message Footer
This change has nothing to do with the changes addressed by the issue, please undo this one.

2019-09-13 10:40 UTC, bwbohl commented
Now that we bugfixed MEI 4 I think we can move on with this, as Part of MEI 4.1

2020-01-07 07:34 UTC, craigsapp commented
How is incorporating this feature going?  This would be very useful for encoding parts sharing the same staff in orchestral scores.  I.e., the parts can be stored in two layers in the data allowing the parts to be easily separated (useful for part extraction), but the visual syntax could be a single layer with chords when the rhythms of the two parts match.  So in other words, it would be useful to have this feature available for those working on orchestral or other large scores so that they can encode optimally (and not have to recode it later :-).

2020-02-17 16:05 UTC, frakel commented
I added now some lines in the documentation as @kepper asked. 
@bwbohl: As the original fork does no longer exist I hope you can nonetheless merge just the MEI.shared.xml file and ignore any other change I made in that branch. Otherwise I would have to make a new PR from another fork ...

2020-10-16 09:56 UTC, kepper commented
we need to resolve the conflicts, but other than that, this seems fine with me

2020-10-29 13:57 UTC, kepper commented
closed by https://github.com/music-encoding/music-encoding/commit/8ed927144666dcfc57246bcf90736065038ebb61. Thanks @frakel for your work on this, and apologies for the long delay…

2020-10-29 13:57 UTC, closed without merging