Move rotate attribute to att.coordinated
music-encoding/music-encoding pull request #681
Opened 2020-06-25 16:45 UTC by JRegimbal

This makes `@rotate` apply to all elements with the `att.coordinated` class and not just the `zone` element. This expands it to the `surface` and `symbolDef` elements.

See #674 for more information on `@rotate`.

2020-06-26 09:59 UTC, kepper requested changes
I think in general it's better to move this up to att.coordinated. I'm not perfectly sure if I'd prefer to see it in a separate sub-class or not. Normally, I would, but considering where this occurs, I think it's fine to put placement and rotation in one class. What I'm more concerned with is the description. @JRegimbal's clarification in a18fee061b0e5c69f4b8410aca68cfbc60a9b1fd helped, but didn't fully fix it in my perception. Ideally, we should have an image somewhere in the documentation, both in the Guidelines and here as a remark (compare with https://music-encoding.org/guidelines/v4/data-types/data.accidental.written.html). It should be absolutely clear what the center of the rotation is, and if the two points encoded by ulx/uly and lrx/lry are already rotated (so that width and height of that rect can't be derived directly anymore, but one could add att.dimensions to compensate). I'd really like to see more explicit statements about all this before putting it in, even though it's certainly going in the right direction :-) 

2020-06-29 12:18 UTC, JRegimbal commented
My impression of how `@rotate` would apply to the other two elements is that, like in `zone`, the bounding box defined by ulx/uly/lrx/lry would not be impacted by rotation but would inform the user or software that the content should be interpreted as rotated.

So for something like `<surface rotation="45">...</surface>` that would mean that the entire surface described (including any zones in it) should by default be interpreted as being captured at a 45° angle. Similarly `<symbolDef rotation="15">...</symbolDef>` would mean that the symbol being defined should be interpreted as rotated 15° from whatever it's normal orientation would be. But in both cases the x-y plane would be unaffected.

Does this seem like a sensible interpretation to you @lpugin and @kepper? If so I can add another commit making this explicit.

2020-07-01 07:23 UTC, bwbohl requested changes
Unfortunately I missed the addition of `@rotate` in the first place… At the moment I'm in eager need of some real world examples for `@rotate`. As of the name  (picking up the question is it the zone or the content that are being rotated) why not pick @`rotated` which makes it clear in the current facsimile context. (then why limit it to theses facsimile elements? What about born digital documents?)
Concerning `symbolDef` I'd see more sense in adding`@rotate(d)` to `symbol`as otherwise one would need multiple `symbolDef` just to encode a normal and rotated version of a symbol.

2020-07-01 07:23 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +          Indicates the amount by which the contents of this zone have been rotated clockwise, with respect
The description is still referring to `mei:zone` if `@rotate` is to be moved to `att.rotated`this should be generalised

2020-07-01 07:23 UTC, bwbohl commented on source/modules/MEI.shared.xml
> +          context="mei:relationList/mei:relation[parent::mei:work or parent::mei:expression or
It's nice that this PR fixes those trailing whitespaces but for the sake of reviewing it would be better not to include such changes ;-)

2020-07-01 14:07 UTC, JRegimbal commented on source/modules/MEI.shared.xml
> +          Indicates the amount by which the contents of this zone have been rotated clockwise, with respect
Oh thanks nice I missed that!

2020-07-01 14:08 UTC, JRegimbal commented on source/modules/MEI.shared.xml
> +          context="mei:relationList/mei:relation[parent::mei:work or parent::mei:expression or
Ah sorry about that my editor is very aggressive with trailing whitespace.

2020-08-31 08:45 UTC, lpugin commented
Anything wrong with this PR? (This is currently blocking the update of the Schema within Verovio)

2020-08-31 08:54 UTC, bwbohl commented
need a small fix in the documentation I'd say, sorry for the delay: https://github.com/music-encoding/guidelines/pull/178

2020-09-22 14:20 UTC, lpugin commented
How does it look now?

2020-10-15 10:21 UTC, kepper approved these changes
Apologies for the long wait – this is definitely ready for merge, just as https://github.com/music-encoding/guidelines/pull/178# (to be done tomorrow at the ODD Friday…)

2020-10-16 12:58 UTC, merged

2022-11-01 08:41 UTC, rettinghaus commented
Could we revert this particular change? (Yes, I know I'm late to the party.) I don't see the sense in having `@rotate` on `surface`. The encoding always follow the main text direction. You would not encode music/text upside down, just because you're too lazy to rotate the folio in front of you.  
Same for `symbolDef`. Why would you define a symbol in a rotated state? If one symbol seems to be rotated on the page you would still use `zone`, and that seems to be sufficient.

2022-11-01 09:29 UTC, ahankinson commented
The intention was to be able to capture the offset of the surface from the main text direction. If an image was rotated by 2° during digitization there was no way to capture this such that the notation and the surface could be aligned. You could capture width and height.

It's explained here: https://github.com/music-encoding/music-encoding/pull/620

2022-11-01 09:32 UTC, ahankinson commented
In fact, looking back at that you agreed with this, and actually suggested `@rotate`?

2022-11-01 09:38 UTC, rettinghaus commented
Then a zone of the size of the surface is rotated. (Or `graphic`, not the `surface` itself). 
I agreed with #674. 

Connected to this is actually #971.

2022-11-01 09:47 UTC, ahankinson commented
`graphic` points to an image file, which cannot be rotated by definition, since all image files assume 90° corners. 

`zone` is an area of the surface. We do not allow nested zones, and I agree with the reasons why. It complicates the parsing for very little benefit.

`surface` is the abstract space onto which a `graphic` is projected, and allows the co-ordinates of the `zones` to be addressed. It allows for a global rotation such that all zones on that surface may be adjusted per this co-ordinate space, if the user desires. 

If it helps you can think of a `surface` as a specialized `zone` -- naming it differently means we can enforce a single layer of nesting, since otherwise we would be forced to always allow `zone` within `zone` to arbitrary depths.