Add schematron rules for dur.quality values.
music-encoding/music-encoding pull request #698
Opened 2020-07-28 18:34 UTC by martha-thomae

- Not allowing `"duplex"` quality to be used in any other note than a `"longa"`.
- Not allowing `"maior"` and `"minor"` quality values to be used in any other note than a `"semibrevis"`.

2020-07-30 15:01 UTC, kepper reviewed
The schematron should do what you expect. On second thought, I think its quite clever to use the notes with `@dur.quality` as context, as this seems more specific than `@dur`. So, in general, this is an approval. However, I wonder if we need the reference to Ars antiqua – is this different in Ars nova? If so, would the proposed solution still support it? If not, why mention it specifically here?

2020-07-30 15:03 UTC, kepper requested changes
well, I guess my last comment should have been a request for changes instead ;-) A clarification on the Ars antiqua reference would be much appreciated…

2020-07-30 17:02 UTC, martha-thomae commented
> However, I wonder if we need the reference to Ars antiqua – is this different in Ars nova? If so, would the proposed solution still support it? If not, why mention it specifically here?

Yes, in Ars antiqua you have these 'maior' and 'minor' values for semibreves and the 'duplex' value for longas, but in Ars nova that doesn't happen anymore (the semibreves become 'altera' or 'regular', and the duplex longa is replaced by the maxima). 

The problem is that I cannot check whether the piece is in Ars antiqua or Ars nova because this would be something that you encode on `@notationSubtype`, which can have any string value. So it is something that I cannot add in the constraint of the schematron rule (I just added it as a text), but at least I can help people avoid using these quality values (maior, minor, and duplex) in other note values (e.g., brevis, minima, semiminima, etc.)

Should I remove the 'Ars antiqua' mention? I think it makes it more specific, even though I cannot check for that.

2020-08-27 13:17 UTC, bwbohl commented
@martha-thomae could you please try building the schema, and see whether the schematron constraint makes it into the RNG because this one (as you pointed out) is defined within the classSpec, whereas all others aren't

2020-10-15 14:03 UTC, kepper reviewed
checked everything if it compiles properly, as requested by @bwbohl – it does 👍 Ready to be merged tomorrow, I'd say :-)

2020-10-15 14:04 UTC, kepper approved these changes

2020-10-15 14:51 UTC, martha-thomae commented
> checked everything if it compiles properly, as requested by @bwbohl – it does 👍 Ready to be merged tomorrow, I'd say :-)

It does! I checked it last week :)

2020-10-16 12:27 UTC, merged