fix neume image path -clean
music-encoding/music-encoding pull request #832
Opened 2021-06-23 14:00 UTC by yinanazhou

Corrected neumes image path, and uploaded missing images in the `neume `folder (cleaned). [Notice](https://github.com/music-encoding/music-encoding/discussions/829): the images will only show up when using **command lines** to build HTML files. To make the **Oxygen** method work, the `image `folder needs to be pasted to `music-encoding\source\web` manually.

2021-06-23 14:04 UTC, ahankinson requested changes

2021-06-23 14:04 UTC, ahankinson commented on source/docs/06-neumes.xml
> +                        <cell>
This change seems to lose the 'Connected' and 'Non-connected' labels?

2021-06-23 14:04 UTC, ahankinson commented on source/docs/06-neumes.xml
> +                            <head/>
Is the empty `head` tag required?

2021-06-23 14:29 UTC, yinanazhou commented
Thanks for pointing that out. The labels can be put inside the `<head>` message. The resulting figure caption is going to be `Figure XX. Connected` if we add the label in the empty `<head>` message. We can add the labels if necessary.

2021-06-23 14:30 UTC, ahankinson commented
They seem necessary?

2021-06-23 14:31 UTC, yinanazhou commented
OK! We will add them right now!

2021-06-23 15:36 UTC, ahankinson commented
Great! Thank you.

Just to make it easier to review without needing to download and run the code locally, could you please provide a screenshot of what it looks like now? Just one or two examples showing how the label and image look together would be sufficient.

2021-06-23 15:57 UTC, yinanazhou commented
Hi, we just built it using command lines, and it looks like this now:
![connected](https://user-images.githubusercontent.com/74484576/123129656-1ca8e100-d41a-11eb-8d76-d50bd3a88127.png)
![nc](https://user-images.githubusercontent.com/74484576/123129660-1d417780-d41a-11eb-89a0-e780fa62ea50.png)

2021-06-23 15:59 UTC, ahankinson commented
OK -- do you know where those funny `:-------:` things come from?

2021-06-23 16:02 UTC, ahankinson commented
Ah, looking at it more, it seems that the 'connected' and 'non-connected' labels are in some sort of table? And the `:-----:` is maybe a hangover from the markdown conversion? @bwbohl @kepper do you know anything about this?

Should we clean those up now, or should we open another issue for it?

2021-06-23 16:02 UTC, yinanazhou commented
They are in the [original version](https://github.com/music-encoding/music-encoding/blob/develop/source/docs/06-neumes.xml). We did not change it.
Example (line 123-126): 
```
<row>
      <cell>:---------:</cell>
      <cell>:---------:</cell>
</row>
```

2021-06-23 16:07 UTC, kepper commented
Yes, if I remember correctly, those are artifacts from how figures and captions were organized "creatively" in Markdown. Would be perfect to clean that up while you're at it now… (pretty please ;-) From my perspective, those examples don't need to be written as table, and using a table for layout purposes is generally questionable, isn't it?

2021-06-25 09:23 UTC, ahankinson commented
@yinanazhou would you be able to make the changes?

2021-06-25 10:29 UTC, musicEnfanthen commented
The hyphens within colons mark a "center-aligned" table cell in markdown: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables#formatting-content-within-your-table
All those [`<rows>` artifacts](https://github.com/music-encoding/music-encoding/pull/832#issuecomment-866966889) could be safely removed.

2021-06-25 12:32 UTC, yinanazhou commented
@ahankinson yes, sure. We will do it now.

2021-06-25 13:12 UTC, yinanazhou commented
Hi @ahankinson and @martha-thomae, this is how it looks like now:
![image](https://user-images.githubusercontent.com/74484576/123429893-7e418a80-d595-11eb-989b-e36f3b49c8b8.png)

2021-06-25 13:15 UTC, ahankinson commented
Looks much better! Thank you.

@martha-thomae @kepper would you be willing to be the second approver on this PR? If so, feel free to merge if you're happy.

2021-06-25 13:16 UTC, ahankinson approved these changes

2021-06-28 08:36 UTC, bwbohl approved these changes

2021-06-28 08:36 UTC, merged