Improve anyStart schema
music-encoding/music-encoding pull request #874
Opened 2021-11-04 23:16 UTC by bwbohl

This PR improves the anyStart schema by:
 
 * adding `@meiversion` (actually `att.meiVersion`) to `att.basic` and thus allowing it on any element, and consequently to prevent duplicate attributes, removing it from the elements that could have `@meiversion`before.
 * adding a schematron rule to assert `@meiversion`is present on the root element

2021-11-05 06:56 UTC, rettinghaus approved these changes
Looks good.

2021-11-11 10:35 UTC, ahankinson commented on customizations/mei-all_anyStart.xml
> +            <item>adding a schematron rule to assert `@meiversion`is present on the root element</item>
Missing space between `@meiversion` and `is`.

2021-11-11 10:38 UTC, ahankinson requested changes

2021-11-11 10:38 UTC, ahankinson commented on customizations/mei-all_anyStart.xml
> +              <sch:assert test="/mei:*[@meiversion]">The root element must have the meiversion attribute in order to indicate the version the mei snippet is based on.</sch:assert>
```suggestion
              <sch:assert test="/mei:*[@meiversion]">The root element must have the @meiversion attribute in order to indicate the MEI version of the snippet.</sch:assert>
```

2021-11-11 10:38 UTC, ahankinson commented on customizations/mei-all_anyStart.xml
> +            <item>adding `@meiversion` (actually `att.meiVersion`) to `att.basic` and thus allowing it on any element, and consequently to prevent duplicate attributes, removing it from the elements
Missing space between `@meiversion` and `before`

2021-11-16 08:14 UTC, ahankinson approved these changes

2021-11-16 08:15 UTC, ahankinson commented
Two approving reviews. Merging.

2021-11-16 08:15 UTC, merged

2021-11-16 13:40 UTC, bwbohl commented
Thx @ahankinson