Fix/934
music-encoding/music-encoding pull request #992
Opened 2022-09-22 07:31 UTC by bwbohl

As `<exhibHist>`, `<treatHist>` and `<treatSched>` have been remodelled after `<provenance>` in [#911](https://github.com/music-encoding/music-encoding/issues/911), the corresponding Schematron rule to report an error in work and expression contexts had to be updated. Moreover, in [#934](https://github.com/music-encoding/music-encoding/issues/934), we agreed also to apply this rule to the manifestation context if the manifestation is not a singleton.
This PR applies the necessary changes.

2022-09-22 09:00 UTC, rettinghaus submitted a review, later dismissed
Looks good to me, thanks!

2022-09-23 16:48 UTC, doerners requested changes
The schematron rule looks find to me, thanks @bwbohl! However, I noticed two things I think should be changed within the description:

1. Not all elements affected by the schematron rule are listed within the description. I think it would be good to list all of them.
2. My impression was that expression and manifestation were mixed up in the second half of the description – if I'm not totally mistaken there is no singleton expression.

The wording I provided is just a suggestion and I'm not set that it has to stay like this :)

2022-09-23 16:48 UTC, doerners commented on source/modules/MEI.header.xml
> +            elements are not permitted in the work context or expression context, if expression is not singleton.</sch:assert>
```suggestion
          <sch:assert test="not(mei:acquisition or mei:provenance or mei:exhibHist or mei:treatHist or mei:treatSched)">The elements acquisition, provenance, exhibHist, treatHist and treatSched are not permitted at the work or expression level and are only permitted at the manifestation level, if the manifestation is a manifestation singleton.</sch:assert>
```

2022-09-27 14:55 UTC, bwbohl commented
thanks for the valuable contribution @doerners ! Merged it, If you would be so kind as to update your review ;-)

2022-09-27 15:38 UTC, doerners approved these changes
Thanks @bwbohl looks great!

2022-09-27 15:46 UTC, rettinghaus approved these changes
Even better!

2022-09-27 19:05 UTC, merged